// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 定义需要的结构体
type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// 增
type InsertUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertUserReq) Reset()         { *m = InsertUserReq{} }
func (m *InsertUserReq) String() string { return proto.CompactTextString(m) }
func (*InsertUserReq) ProtoMessage()    {}
func (*InsertUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *InsertUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertUserReq.Unmarshal(m, b)
}
func (m *InsertUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertUserReq.Marshal(b, m, deterministic)
}
func (m *InsertUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertUserReq.Merge(m, src)
}
func (m *InsertUserReq) XXX_Size() int {
	return xxx_messageInfo_InsertUserReq.Size(m)
}
func (m *InsertUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_InsertUserReq proto.InternalMessageInfo

func (m *InsertUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertUserReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type InsertUserRep struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertUserRep) Reset()         { *m = InsertUserRep{} }
func (m *InsertUserRep) String() string { return proto.CompactTextString(m) }
func (*InsertUserRep) ProtoMessage()    {}
func (*InsertUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *InsertUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertUserRep.Unmarshal(m, b)
}
func (m *InsertUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertUserRep.Marshal(b, m, deterministic)
}
func (m *InsertUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertUserRep.Merge(m, src)
}
func (m *InsertUserRep) XXX_Size() int {
	return xxx_messageInfo_InsertUserRep.Size(m)
}
func (m *InsertUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_InsertUserRep proto.InternalMessageInfo

func (m *InsertUserRep) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertUserRep) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertUserRep) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertUserRep) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// 删
type DeleteUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReq) Reset()         { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()    {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *DeleteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReq.Unmarshal(m, b)
}
func (m *DeleteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReq.Marshal(b, m, deterministic)
}
func (m *DeleteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReq.Merge(m, src)
}
func (m *DeleteUserReq) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReq.Size(m)
}
func (m *DeleteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReq proto.InternalMessageInfo

func (m *DeleteUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRep) Reset()         { *m = DeleteUserRep{} }
func (m *DeleteUserRep) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRep) ProtoMessage()    {}
func (*DeleteUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *DeleteUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRep.Unmarshal(m, b)
}
func (m *DeleteUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRep.Marshal(b, m, deterministic)
}
func (m *DeleteUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRep.Merge(m, src)
}
func (m *DeleteUserRep) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRep.Size(m)
}
func (m *DeleteUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRep proto.InternalMessageInfo

// 改
type ModifyUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserReq) Reset()         { *m = ModifyUserReq{} }
func (m *ModifyUserReq) String() string { return proto.CompactTextString(m) }
func (*ModifyUserReq) ProtoMessage()    {}
func (*ModifyUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *ModifyUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserReq.Unmarshal(m, b)
}
func (m *ModifyUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserReq.Marshal(b, m, deterministic)
}
func (m *ModifyUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserReq.Merge(m, src)
}
func (m *ModifyUserReq) XXX_Size() int {
	return xxx_messageInfo_ModifyUserReq.Size(m)
}
func (m *ModifyUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserReq proto.InternalMessageInfo

func (m *ModifyUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifyUserReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ModifyUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// 改
type ModifyUserRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserRep) Reset()         { *m = ModifyUserRep{} }
func (m *ModifyUserRep) String() string { return proto.CompactTextString(m) }
func (*ModifyUserRep) ProtoMessage()    {}
func (*ModifyUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *ModifyUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserRep.Unmarshal(m, b)
}
func (m *ModifyUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserRep.Marshal(b, m, deterministic)
}
func (m *ModifyUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserRep.Merge(m, src)
}
func (m *ModifyUserRep) XXX_Size() int {
	return xxx_messageInfo_ModifyUserRep.Size(m)
}
func (m *ModifyUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserRep proto.InternalMessageInfo

// 查
type SelectUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectUserReq) Reset()         { *m = SelectUserReq{} }
func (m *SelectUserReq) String() string { return proto.CompactTextString(m) }
func (*SelectUserReq) ProtoMessage()    {}
func (*SelectUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *SelectUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectUserReq.Unmarshal(m, b)
}
func (m *SelectUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectUserReq.Marshal(b, m, deterministic)
}
func (m *SelectUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectUserReq.Merge(m, src)
}
func (m *SelectUserReq) XXX_Size() int {
	return xxx_messageInfo_SelectUserReq.Size(m)
}
func (m *SelectUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_SelectUserReq proto.InternalMessageInfo

func (m *SelectUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SelectUserRep struct {
	Users                *User    `protobuf:"bytes,1,opt,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectUserRep) Reset()         { *m = SelectUserRep{} }
func (m *SelectUserRep) String() string { return proto.CompactTextString(m) }
func (*SelectUserRep) ProtoMessage()    {}
func (*SelectUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *SelectUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectUserRep.Unmarshal(m, b)
}
func (m *SelectUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectUserRep.Marshal(b, m, deterministic)
}
func (m *SelectUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectUserRep.Merge(m, src)
}
func (m *SelectUserRep) XXX_Size() int {
	return xxx_messageInfo_SelectUserRep.Size(m)
}
func (m *SelectUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_SelectUserRep proto.InternalMessageInfo

func (m *SelectUserRep) GetUsers() *User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*InsertUserReq)(nil), "pb.InsertUserReq")
	proto.RegisterType((*InsertUserRep)(nil), "pb.InsertUserRep")
	proto.RegisterType((*DeleteUserReq)(nil), "pb.DeleteUserReq")
	proto.RegisterType((*DeleteUserRep)(nil), "pb.DeleteUserRep")
	proto.RegisterType((*ModifyUserReq)(nil), "pb.ModifyUserReq")
	proto.RegisterType((*ModifyUserRep)(nil), "pb.ModifyUserRep")
	proto.RegisterType((*SelectUserReq)(nil), "pb.SelectUserReq")
	proto.RegisterType((*SelectUserRep)(nil), "pb.SelectUserRep")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x6d, 0x42, 0xc2, 0xc7, 0x45, 0xa5, 0xe2, 0xc4, 0x60, 0x65, 0x80, 0xca, 0x53, 0xa7, 0x20,
	0x95, 0xf2, 0x0f, 0x58, 0x18, 0x58, 0x52, 0xb1, 0xb0, 0x35, 0xf1, 0x21, 0x22, 0x95, 0xe4, 0xb0,
	0x03, 0x12, 0x7f, 0x98, 0xdf, 0x81, 0x6c, 0x83, 0x82, 0x15, 0x75, 0x6c, 0xb7, 0xdc, 0xcb, 0x7b,
	0x7a, 0xf7, 0x9e, 0x6d, 0x80, 0x0f, 0x43, 0xba, 0x60, 0xdd, 0xf5, 0x1d, 0xc6, 0x5c, 0xc9, 0x67,
	0x48, 0x9e, 0x0c, 0x69, 0x3c, 0x87, 0xb8, 0x51, 0x22, 0x9a, 0x47, 0x8b, 0xb4, 0x8c, 0x1b, 0x85,
	0x08, 0x49, 0xbb, 0x79, 0x23, 0x11, 0xcf, 0xa3, 0xc5, 0x59, 0xe9, 0xbe, 0x51, 0xc0, 0xc9, 0x46,
	0x29, 0x4d, 0xc6, 0x88, 0x23, 0x07, 0xff, 0x8d, 0x78, 0x09, 0x29, 0xbf, 0x76, 0x2d, 0x89, 0xc4,
	0xe1, 0x7e, 0x90, 0x35, 0x4c, 0x1f, 0x5a, 0x43, 0xba, 0xb7, 0x0e, 0x25, 0xbd, 0x1f, 0xc2, 0x84,
	0xf7, 0x62, 0x72, 0x0d, 0xd3, 0x7b, 0xda, 0x52, 0x4f, 0x3b, 0x92, 0xc8, 0x59, 0x48, 0x60, 0xbb,
	0xd6, 0x63, 0xa7, 0x9a, 0x97, 0xaf, 0x7d, 0x66, 0x9f, 0x85, 0x26, 0x6c, 0xf7, 0x5c, 0xd3, 0x96,
	0xea, 0x5d, 0x8d, 0xcb, 0x9b, 0x90, 0xc0, 0x78, 0x05, 0xa9, 0xbd, 0x11, 0xc6, 0x71, 0xb2, 0xe5,
	0x69, 0xc1, 0x55, 0xe1, 0xfe, 0x79, 0x78, 0xf9, 0x1d, 0x41, 0x66, 0xe7, 0x35, 0xe9, 0xcf, 0xa6,
	0x26, 0x5c, 0x01, 0x0c, 0x75, 0xe3, 0x85, 0xa5, 0x07, 0x67, 0x9c, 0x8f, 0x20, 0x96, 0x13, 0xbc,
	0x83, 0xcc, 0xd7, 0xf3, 0x4f, 0x16, 0x14, 0x9a, 0x8f, 0x20, 0x2b, 0x5b, 0x01, 0x0c, 0xf9, 0xbc,
	0x2a, 0x28, 0x35, 0x1f, 0x41, 0xbf, 0xaa, 0x21, 0xa3, 0x57, 0x05, 0xa5, 0xe4, 0x23, 0x88, 0xe5,
	0xa4, 0x3a, 0x76, 0x6f, 0xe2, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x56, 0x14, 0xec, 0x21,
	0x03, 0x00, 0x00,
}
